server:
  port: 9191
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/profileDB?createDatabaseIfNotExist=true
    username: root
    password: pass!1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl